# stages:
#   - build
#   - cube_reproject
#   - evaluate
#
# before_script:
#   - export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
#   - export PATH=$PATH:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
#   - export CUDA_HOME=/usr/local/cuda
#
# compile:
#   stage: build
#   script:
#     - make -j4
#     - echo "make"
#
# # Perform unit tests
# unit_tests:
#   stage: cube_reproject
#   script:
#     - bash util/CI/unit_test01.sh
#     - bash util/CI/unit_test02.sh

stages:
  - build
  - documentation

compile:
  stage: build
  script:
    - make -j4
    - echo "Build successful"

pages:
  stage: documentation
  script:
  - doxygen ./doc/doxygen/Doxyfile
  - mkdir public
  - mv ./doc/doxygen/documentation/html/ public
  artifacts:
    paths:
    - public
  only:
  - master
