stages:
  - documentation
  - build

pages:
  stage: documentation
  script:
  - doxygen ./doc/doxygen/Doxyfile
  - mkdir ./doc/doxygen/public
  - mv ./doc/doxygen/documentation/html/ ./doc/doxygen/public
  artifacts:
    paths:
    - ./doc/doxygen/public
  only:
  - master

build-job:
  stage: build
  script:
    - echo "Hello world"
  only:
    - merge_requests

