
stages:
  - build
  - test
  - evaluate

before_script:
  - export PATH=$LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:

compile:
  stage: build
  script: make


# Perform unit tests
unit_tests:
  script: ./util/CI/unit_test1.sh

