stages:
  - documentation
  - build

pages:
  stage: documentation
  script:
  - doxygen ./doc/doxygen/Doxyfile
  - mkdir ./doc/doxygen/public
  - mv ./doc/doxygen/documentation/html/ ./doc/doxygen/public
  artifacts:
    paths:
    - ./doc/doxygen/public
  only:
  - master

build-job-ruby:
  stage: build
  script:
    - echo "Hello world"
  tags:
    - ruby
  only:
    - merge_requests

build-job-ssh:
  stage: build
  script:
    - scripts/run-script.sh scripts/sub-build.sh
  tags:
    - gacrc
  only:
    - merge_requests
