stages:
  - documentation
  - build

pages:
  stage: documentation
  script:
  - doxygen ./doc/doxygen/Doxyfile
  - mkdir ./doc/doxygen/public
  - mv ./doc/doxygen/documentation/html/ ./doc/doxygen/public
  artifacts:
    paths:
    - ./doc/doxygen/public
  only:
  - master

build-job-ruby:
  stage: build
  script:
    - echo "Hello world"
  tags:
    - ruby
  only:
    - merge_requests

build-job-ssh:
  stage: build
  script:
    - j=$(sbatch scripts/sub-build.sh | awk '{print $4}')
    - echo "PENDING"
    - "while [ $(sacct -j $j -X | tail -n1 | awk '{print $6}') == 'PENDING' ]; do :; done"
    - echo "RUNNING"
    - "while [ $(sacct -j $j -X | tail -n2 | awk '{print $6}') == 'RUNNING' ]; do :; done"
    - echo "DONE"
  tags:
    - gacrc
  only:
    - merge_requests
