stages:
  - build
  - test
  - evaluate

before_script:
  - export PATH=/usr/local/cuda-9.0/bin${PATH:+:${PATH}}
  - export PATH=$PATH:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
  - export CUDA_HOME=/usr/local/cuda

compile:
  stage: build
  script:
    - make -j4
    - echo "make"

# Perform unit tests
unit_tests:
  stage: test
  script:
    - bash util/CI/unit_test01.sh
    - bash util/CI/unti_test02.sh
